2023-04-21 17:50:43,440 - root - INFO - Authorization succeed.
2023-04-21 17:50:43,787 - numexpr.utils - INFO - NumExpr defaulting to 4 threads.
2023-04-21 17:50:44,100 - werkzeug - INFO -  * Detected change in 'D:\\Anaconda3\\Lib\\site-packages\\pandas\\core\\apply.py', reloading
2023-04-21 17:50:44,113 - werkzeug - INFO -  * Detected change in 'D:\\Anaconda3\\Lib\\site-packages\\pandas\\core\\__pycache__\\apply.cpython-38.pyc', reloading
2023-04-21 17:50:44,120 - root - ERROR - [Errno 2] No such file or directory: './src_fig/head-1@2x.png'
Traceback (most recent call last):
  File "e:\zc\GitProjects\algorithm-platform\platform\head_move\server.py", line 99, in balance
    balancer.draw_sav(txt_head_data, mode, n, './src_fig/', out_path+'/result_fig/'+"traj{}.png".format(n))
  File "e:\zc\GitProjects\algorithm-platform\platform\head_move\Balance.py", line 271, in draw_sav
    draw_1(mode)
  File "e:\zc\GitProjects\algorithm-platform\platform\head_move\Balance.py", line 65, in draw_1
    raise e
  File "e:\zc\GitProjects\algorithm-platform\platform\head_move\Balance.py", line 63, in draw_1
    im_xz = plt.imread(read_path + '{}-{}@2x.png'.format(mode, 1))
  File "D:\Anaconda3\lib\site-packages\matplotlib\pyplot.py", line 2246, in imread
    return matplotlib.image.imread(fname, format)
  File "D:\Anaconda3\lib\site-packages\matplotlib\image.py", line 1496, in imread
    with img_open(fname) as image:
  File "D:\Anaconda3\lib\site-packages\PIL\ImageFile.py", line 109, in __init__
    self.fp = open(fp, "rb")
FileNotFoundError: [Errno 2] No such file or directory: './src_fig/head-1@2x.png'
2023-04-21 17:50:44,157 - werkzeug - INFO - 127.0.0.1 - - [21/Apr/2023 17:50:44] "[37mPOST /balance HTTP/1.1[0m" 200 -
