2023-02-19 11:02:40,548 - root - INFO - Authorization succeed.
2023-02-19 11:02:40,983 - numexpr.utils - INFO - NumExpr defaulting to 4 threads.
2023-02-19 11:02:42,311 - root - INFO - traj1 completed.
2023-02-19 11:02:43,203 - root - INFO - traj2 completed.
2023-02-19 11:02:44,077 - root - INFO - traj3 completed.
2023-02-19 11:02:44,081 - root - INFO - Velocity calculated.
2023-02-19 11:02:44,081 - root - INFO - --------------------------------
2023-02-19 11:02:44,082 - root - INFO - Forth: 22.89
2023-02-19 11:02:44,082 - root - INFO - Back: -9.00
2023-02-19 11:02:44,082 - root - INFO - Left: 19.99
2023-02-19 11:02:44,082 - root - INFO - Right: -8.97
2023-02-19 11:02:44,082 - root - INFO - Up: 4.02
2023-02-19 11:02:44,082 - root - INFO - Down: -4.35
2023-02-19 11:02:44,082 - root - INFO - --------------------------------
2023-02-19 11:02:44,082 - root - INFO - Succeed rates calculated.
2023-02-19 11:02:44,082 - root - INFO - Right_forth: suc--80.85% pct--51.09%
2023-02-19 11:02:44,082 - root - INFO - Left_forth: suc--80.00% pct--48.91%
2023-02-19 11:02:44,082 - root - INFO - Left_back: suc--0.00% pct--0.00%
2023-02-19 11:02:44,082 - root - INFO - Right_back: suc--0.00% pct--0.00%
2023-02-19 11:02:44,082 - root - INFO - --------------END---------------
2023-02-19 11:02:44,083 - werkzeug - INFO - 127.0.0.1 - - [19/Feb/2023 11:02:44] "[37mPOST /balance HTTP/1.1[0m" 200 -
2023-02-19 11:03:57,698 - root - INFO - Authorization succeed.
2023-02-19 11:03:58,407 - root - ERROR - [Errno 2] No such file or directory: './src_fig_pp/table@2x.png'
Traceback (most recent call last):
  File "e:\zc\GitProjects\algorithm-platform\platform\head_move\server.py", line 164, in pingpong
    pp.traj_draw(data=raw_data)
  File "e:\zc\GitProjects\algorithm-platform\platform\head_move\Pingpong.py", line 74, in traj_draw
    self.traj_table(data, r_pth, w_pth)
  File "e:\zc\GitProjects\algorithm-platform\platform\head_move\Pingpong.py", line 101, in traj_table
    im = plt.imread(read_pth+'/table@2x.png')
  File "D:\Anaconda3\lib\site-packages\matplotlib\pyplot.py", line 2246, in imread
    return matplotlib.image.imread(fname, format)
  File "D:\Anaconda3\lib\site-packages\matplotlib\image.py", line 1496, in imread
    with img_open(fname) as image:
  File "D:\Anaconda3\lib\site-packages\PIL\ImageFile.py", line 109, in __init__
    self.fp = open(fp, "rb")
FileNotFoundError: [Errno 2] No such file or directory: './src_fig_pp/table@2x.png'
2023-02-19 11:03:58,417 - werkzeug - INFO - 127.0.0.1 - - [19/Feb/2023 11:03:58] "[37mPOST /pingpong HTTP/1.1[0m" 200 -
2023-02-19 11:05:29,670 - werkzeug - INFO -  * Detected change in 'e:\\zc\\GitProjects\\algorithm-platform\\platform\\head_move\\Balance.py', reloading
