2023-02-19 11:03:57,698 - root - INFO - Authorization succeed.
2023-02-19 11:03:58,407 - root - ERROR - [Errno 2] No such file or directory: './src_fig_pp/table@2x.png'
Traceback (most recent call last):
  File "e:\zc\GitProjects\algorithm-platform\platform\head_move\server.py", line 164, in pingpong
    pp.traj_draw(data=raw_data)
  File "e:\zc\GitProjects\algorithm-platform\platform\head_move\Pingpong.py", line 74, in traj_draw
    self.traj_table(data, r_pth, w_pth)
  File "e:\zc\GitProjects\algorithm-platform\platform\head_move\Pingpong.py", line 101, in traj_table
    im = plt.imread(read_pth+'/table@2x.png')
  File "D:\Anaconda3\lib\site-packages\matplotlib\pyplot.py", line 2246, in imread
    return matplotlib.image.imread(fname, format)
  File "D:\Anaconda3\lib\site-packages\matplotlib\image.py", line 1496, in imread
    with img_open(fname) as image:
  File "D:\Anaconda3\lib\site-packages\PIL\ImageFile.py", line 109, in __init__
    self.fp = open(fp, "rb")
FileNotFoundError: [Errno 2] No such file or directory: './src_fig_pp/table@2x.png'
2023-02-19 11:03:58,417 - werkzeug - INFO - 127.0.0.1 - - [19/Feb/2023 11:03:58] "[37mPOST /pingpong HTTP/1.1[0m" 200 -
2023-02-19 11:05:29,670 - werkzeug - INFO -  * Detected change in 'e:\\zc\\GitProjects\\algorithm-platform\\platform\\head_move\\Balance.py', reloading
